name: 'Notify'
description: 'Send notification to your destination'
author: 'adobaai'
inputs:
  dryRun:
    required: false
    description: 'Dry run notifying or not'
  title:
    required: true
    description: 'The title of the notification'
  content:
    description: 'The content of the notification (Markdown is supported)'
  command:
    description: 'The command will be used as the content of the notification'
  larkBotWebhook:
    required: true
    description: 'The webhook url of the Lark bot'
runs:
  using: 'node16'
  main: 'dist/index.js'
