name: 'Notify'
description: 'Send notification to your destination'
author: 'adobaai'
inputs:
  dryRun:
    required: false
    description: 'Dry run notifying or not'
  title:
    required: true
    description: 'The title of the nofification'
  command:
    required: true
    description: 'The command to be executed'
  larkBotWebhook:
    required: true
    description: 'The webhook url of the Lark bot'
runs:
  using: 'node16'
  main: 'dist/index.js'
